export interface Lead {
    leadId:number,
    leadOwnerId:number,
      companyName:string,
      leadStatusId:number,
      leadSourceId:number ,
      firstName:string ,
      email:string ,
      phone1:string ,
      website: string,
      shipmentType: string,
      monthlyTeus: number,
      pol: string,
      pod: string,
      industryId:number ,
      annualRevenue:number ,
      employeeCount: string,
      emailOptIn: boolean,
      countryId: number,
      stateId: number,
      cityName:string ,
      zipcode: string,
      street: string
}