export interface Lead {
    leadId:number,
    leadOwnerId:number,
      companyName:string,
      leadOwnerName?:string,
      leadStatusId:number,
      leadStatusName?:string,
      leadSourceId:number ,
      leadSourceName?:string,
      firstName:string ,
      email:string ,
      phone1:string ,
      website: string,
      shipmentType: string,
      monthlyTeus: number,
      pol: string,
      pod: string,
      industryId:number ,
      industryName?:string,
      annualRevenue:number ,
      employeeCount: string,
      emailOptIn: boolean,
      countryId: number,
      stateId: number,
      cityName:string ,
      zipcode: string,
      street: string,
      stateName ?: string,
      countryName?:string,
      zipCode?:string
}